{% set version = "1.4.0" %}

package:
  name: qtpy
  version: {{version}}

source:
  fn: qtpy-{{version}}.tar.gz
  url: https://pypi.io/packages/source/q/qtpy/QtPy-{{version}}.tar.gz
  sha256: 8e78e7ce28015c1041be68b90f43048c9815e8c89d3362f8073feecdc70eafba

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:

  host:
    - python
    - setuptools

  run:
    - python

test:
  requires:
    - pyqt
  imports:
    - qtpy
    - qtpy.QtGui

about:
  home: https://github.com/spyder-ide/qtpy
  license: MIT
  summary: Abtraction layer for PyQt5/PyQt4/PySide
  description: |
    QtPy is a small abstraction layer that lets you write applications using a
    single api call to either PyQt or PySide.

extra:
  recipe-maintainers:
    - ccordoba12
    - goanpeca
    - astrofrog-conda-forge
    - Nodd
