{% set version = "1.11.2" %}

package:
  name: qtpy
  version: {{version}}

source:
  fn: qtpy-{{version}}.tar.gz
  url: https://pypi.io/packages/source/q/qtpy/QtPy-{{version}}.tar.gz
  sha256: d6e4ae3a41f1fcb19762b58f35ad6dd443b4bdc867a4cb81ef10ccd85403c92b

build:
  noarch: python
  number: 0
  # skip s390x due to pyqt missing on s390x
  skip: True  # [py<36 or ppc64le or s390x]
  script: python -m pip install --no-deps --ignore-installed .

requirements:

  host:
    - pip
    - python
    - setuptools
    - wheel

  run:
    - python >=3.6

test:
  requires:
    - pyqt
    - pip
    - python <3.10
  imports:
  script:
    - QT_API=pyqt5 qtpy
    - QT_API=pyqt5 qtpy.QtGui
  commands:
    - pip check

about:
  home: https://github.com/spyder-ide/qtpy
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Abtraction layer for PyQt5/PyQt4/PySide
  description: |
    QtPy is a small abstraction layer that lets you write applications using a
    single api call to either PyQt or PySide.
  doc_url: https://pypi.python.org/pypi/QtPy
  dev_url: https://github.com/spyder-ide/qtpy
  doc_source_url: https://github.com/spyder-ide/qtpy/blob/master/README.md

extra:
  recipe-maintainers:
    - ccordoba12
    - goanpeca
    - astrofrog-conda-forge
    - Nodd
