{% set version = "2.2.0" %}

package:
  name: qtpy
  version: {{version}}

source:
  fn: qtpy-{{version}}.tar.gz
  url: https://pypi.io/packages/source/q/qtpy/QtPy-{{version}}.tar.gz
  sha256: d85f1b121f24a41ad26c55c446e66abdb7c528839f8c4f11f156ec4541903914

build:
  number: 0
  # skip s390x and ppc64le due to pyqt missing on s390x and ppc64le
  skip: True  # [py<37 or s390x or ppc64le]
  script: python -m pip install --no-deps --ignore-installed . -vv
  entry_points:
    - 

requirements:

  host:
    - pip
    - python
    - setuptools >=42
    - wheel
  run:
    - python
    - packaging

test:
  requires:
    - pyqt
    - pip
  imports:
    - qtpy
    - qtpy.QtGui
  script:
    - QT_API=pyqt5 qtpy
    - QT_API=pyqt5 qtpy.QtGui
  commands:
    - pip check

about:
  home: https://github.com/spyder-ide/qtpy
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  license_url: https://github.com/spyder-ide/qtpy/blob/master/LICENSE.txt
  summary: Abtraction layer for PyQt5/PyQt4/PySide
  description: |
    QtPy is a small abstraction layer that lets you write applications using a
    single api call to either PyQt or PySide.
  doc_url: https://pypi.python.org/pypi/QtPy
  dev_url: https://github.com/spyder-ide/qtpy
  doc_source_url: https://github.com/spyder-ide/qtpy/blob/master/README.md

extra:
  recipe-maintainers:
    - ccordoba12
    - goanpeca
    - astrofrog-conda-forge
    - Nodd
