{% set version = "2.4.3" %}

package:
  name: qtpy
  version: {{version}}

source:
  url: https://pypi.io/packages/source/q/qtpy/qtpy-{{ version }}.tar.gz
  sha256: db744f7832e6d3da90568ba6ccbca3ee2b3b4a890c3d6fbbc63142f6e4cdf5bb

build:
  number: 0
  skip: True  # [py<37]
  script: python -m pip install --no-deps --ignore-installed --no-build-isolation . -vv
  entry_points:
    - qtpy = qtpy.__main__:main

requirements:

  host:
    - pip
    - python
    - setuptools >=42
    - wheel
  run:
    - python
    - packaging

test:
  requires:
    - pip
    - pytest >=6,!=7.0.0,!=7.0.1
    - pytest-qt
    - pyqt >=6
  imports:
    - qtpy
    - qtpy.QtCore
    - qtpy.QtDBus
    - qtpy.QtDesigner
    - qtpy.QtGui
    - qtpy.QtHelp
    - qtpy.QtNetwork
    - qtpy.QtOpenGL
    - qtpy.QtOpenGLWidgets
    - qtpy.QtPrintSupport
    - qtpy.QtQml
    - qtpy.QtQuick
    - qtpy.QtQuickWidgets
    - qtpy.QtSql
    - qtpy.QtSvg
    - qtpy.QtSvgWidgets
    - qtpy.QtTest
    - qtpy.QtWebChannel
    - qtpy.QtWebSockets
    - qtpy.QtWidgets
    - qtpy.QtXml
  commands:
    - pip check
    - qtpy mypy-args
    - qtpy --help
    # Our Qt release does not provide QtMultimedia support. Skip these tests for now.
    {% set tests_to_skip = "qtmultimedia" %}
    {% set tests_to_skip = tests_to_skip ~ " or test_qfontmetrics_width" %}  # [linux]
    {% set tests_to_skip = tests_to_skip ~ " or qtgui or qtwidgets" %}       # [osx]
    {% set tests_to_skip = tests_to_skip ~ " or test_QSomethingEvent_pos_functions or test_QMenu_functions" %}  # [win]
    - pytest --pyargs qtpy -k "not ({{ tests_to_skip }})"  # [not linux]
    - xvfb-run -a --server-args="-screen 0 1024x768x24" pytest --pyargs qtpy -k "not ({{ tests_to_skip }})"  # [linux]

about:
  home: https://github.com/spyder-ide/qtpy
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Abstraction layer for PyQt5/PyQt6/PySide2/PySide6
  description: |
    QtPy is a small abstraction layer that lets you write applications using a
    single api call to either PyQt or PySide.
  doc_url: https://github.com/spyder-ide/qtpy
  dev_url: https://github.com/spyder-ide/qtpy

extra:
  recipe-maintainers:
    - ccordoba12
    - goanpeca
    - astrofrog-conda-forge
    - Nodd
