{% set version = "2.4.1" %}

package:
  name: qtpy
  version: {{version}}

source:
  url: https://pypi.io/packages/source/q/qtpy/QtPy-{{version}}.tar.gz
  sha256: a5a15ffd519550a1361bdc56ffc07fda56a6af7292f17c7b395d4083af632987

build:
  number: 0
  # skip s390x and ppc64le due to pyqt missing on s390x and ppc64le
  skip: True  # [py<37 or s390x or ppc64le]
  script: python -m pip install --no-deps --ignore-installed --no-build-isolation . -vv
  entry_points:
    - qtpy = qtpy.__main__:main

requirements:

  host:
    - pip
    - python
    - setuptools >=42
    - wheel
  run:
    - python
    - packaging

test:
  requires:
    - pyqt
    - pip
  imports:
    - qtpy
    - qtpy.QtGui
  script:
    - QT_API=pyqt5 qtpy
    - QT_API=pyqt5 qtpy.QtGui
  commands:
    - pip check

about:
  home: https://github.com/spyder-ide/qtpy
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Abtraction layer for PyQt5/PyQt6/PySide2/PySide6
  description: |
    QtPy is a small abstraction layer that lets you write applications using a
    single api call to either PyQt or PySide.
  doc_url: https://github.com/spyder-ide/qtpy
  dev_url: https://github.com/spyder-ide/qtpy

extra:
  recipe-maintainers:
    - ccordoba12
    - goanpeca
    - astrofrog-conda-forge
    - Nodd
