{% set version = "2.0.0" %}

package:
  name: qtpy
  version: {{version}}

source:
  fn: qtpy-{{version}}.tar.gz
  url: https://pypi.io/packages/source/q/qtpy/QtPy-{{version}}.tar.gz
  sha256: 777e333df4d711b2ec9743117ab319dadfbd743a5a0eee35923855ca3d35cd9d

build:
  noarch: python
  number: 0
  skip: True  # [ppc64le]
  script: python -m pip install --no-deps --ignore-installed .

requirements:

  host:
    - pip
    - python
    - setuptools
    - wheel

  run:
    - python

test:
  requires:
    - pyqt
    - pip
  imports:
  script:
    - QT_API=pyqt5 qtpy
    - QT_API=pyqt5 qtpy.QtGui
  commands:
    - pip check

about:
  home: https://github.com/spyder-ide/qtpy
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Abtraction layer for PyQt5/PyQt4/PySide
  description: |
    QtPy is a small abstraction layer that lets you write applications using a
    single api call to either PyQt or PySide.
  doc_url: https://pypi.python.org/pypi/QtPy
  dev_url: https://github.com/spyder-ide/qtpy
  doc_source_url: https://github.com/spyder-ide/qtpy/blob/master/README.md

extra:
  recipe-maintainers:
    - ccordoba12
    - goanpeca
    - astrofrog-conda-forge
    - Nodd
