{% set version = "2.0.1" %}

package:
  name: qtpy
  version: {{version}}

source:
  fn: qtpy-{{version}}.tar.gz
  url: https://pypi.io/packages/source/q/qtpy/QtPy-{{version}}.tar.gz
  sha256: adfd073ffbd2de81dc7aaa0b983499ef5c59c96adcfdcc9dea60d42ca885eb8f

build:
  noarch: python
  number: 0
  # skip s390x and ppc64le due to pyqt missing on s390x and ppc64le
  script: python -m pip install --no-deps --ignore-installed . -vv

requirements:

  host:
    - pip
    - python
    - setuptools >=42
    - wheel
  run:
    - python >=3.6
    - packaging

test:
  requires:
    - pyqt
    - pip
  imports:
    - qtpy
    - qtpy.QtGui
  script:
    - QT_API=pyqt5 qtpy
    - QT_API=pyqt5 qtpy.QtGui
  commands:
    - pip check

about:
  home: https://github.com/spyder-ide/qtpy
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Abtraction layer for PyQt5/PyQt4/PySide
  description: |
    QtPy is a small abstraction layer that lets you write applications using a
    single api call to either PyQt or PySide.
  doc_url: https://pypi.python.org/pypi/QtPy
  dev_url: https://github.com/spyder-ide/qtpy
  doc_source_url: https://github.com/spyder-ide/qtpy/blob/master/README.md

extra:
  recipe-maintainers:
    - ccordoba12
    - goanpeca
    - astrofrog-conda-forge
    - Nodd
