{% set version = "1.7.0" %}

package:
  name: qtpy
  version: {{version}}

source:
  fn: qtpy-{{version}}.tar.gz
  url: https://pypi.io/packages/source/q/qtpy/QtPy-{{version}}.tar.gz
  sha256: d4c540f1761e794ea26c8dabadabf0173d72e4d1d53c8679aeb31a9e953b4f3e

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:

  host:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  requires:
    - pyqt
  imports:
    - qtpy
    - qtpy.QtGui

about:
  home: https://github.com/spyder-ide/qtpy
  license: MIT
  summary: Abtraction layer for PyQt5/PyQt4/PySide
  description: |
    QtPy is a small abstraction layer that lets you write applications using a
    single api call to either PyQt or PySide.

extra:
  recipe-maintainers:
    - ccordoba12
    - goanpeca
    - astrofrog-conda-forge
    - Nodd
