travis:
  secure:
    BINSTAR_TOKEN: eYumACnKHOwqmHGBBshbP/shko35YC91b0zhvJBmptA81/4eFZ1KVFTNUMoNR0Fln/xVinMbtnrTnLROOcB4adOEzD6j70T67VjDL5s5+0KPoxfSWCTjnDCVwB2fs5gdV5dCDhsGT+vPRKfGjZLfQadE/ksn7PDN1NapEISqGZOkhXu8tSKlpqssyOWfsSEOutJagxiEE0W8BA27imCM1Xoprt2bgWcXqCaA9P74mk9xFIM09FMGS1Yu1Om0lDpGj6khIC7V1buyNVdah2SJiaC8STa6dHuHH4yWT5UjLDjVD0eHYcHK5N3i7xiB6FzLa1fh0By8ZudJuvKQInKV7ULHMZMGXTz8SmfCOxsKl468u7HXn/9jzFG7vvtV8SL/cY30CJZz3KlHLon/IBgw3TTDBlxCeiLveNTWdubUFZWCrPZJgsvKgK2Ok7diA1BQS8YyEN4mTrI0BvX175mm5JFvbyI5UASEuqdbMIoOmglnu6TA8vLI/zUlTBqaFlKLxYuKwB0AaUayTCou3SikjNl34MqJUAfoRLYZX2zlhcNPD9gt4+ukxmiJodgtu1cQQSV9j07fK2ijhA1mnOb/B545i6/8nMMzssY1L/QCzuH4H6pQ8NEo+HoSguic9ZIx/Tun81une3LDv0qoLzlwUGnD9opX7Bfk3Y3543jOW0M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
