travis:
  secure:
    BINSTAR_TOKEN: Qg/Pc6P6PmBgy7hsjuF9FgpwHYn4xgakFHJWTxpRogHn0c0yIXxOeD6U1mmaM142YnRxPa61cfaNg0YcymcW6rhMwRRXGxxAyIMUyb1D6OcOVlI6wJHh1vM65ycVeYrYQpQPS45b7vWTxRBNTHauqmxcGPct7QF/NPeUIgMivOjmWscxu34h3tmm6eIgE8cfJrjz6jYq2IOKPiJWQJjr1/wVlqzQsOxcq0wfboUDdrMWh50LbszMd11hAc1OFYj4MAe3PPXgi6M+atywNE9NEFj3k6B5uFskEhuvS36jljuvLw0emqEpNQL4AaG0gASUQCFfx1VEgioI/XamkhmyQWO1wibIFCBY1feVJKivy06XtKhYhr/PMEZH5+VrXPhh4VpLFiiWx0i6cPykrJ4dw4/+KXK44qsMIbTn74/8m/6M5vUp2Y2bhbFFMvQfjknHSI/6iimXpj5iOO+Ko6myerho6OchXC2Gd5dcH4tKFsm8G9zXL/ZQcRrjlAlOvUsyE8s4qqq591fyUK00TuUtSJPivR9cBRPH9yANCMRyRpMgG6Sq97/G3qoGD1pDjSIIneYld7W3Tgumj47tj1li25W76bOueuqymtKJ1pwWzevyQqW2z2m6FUN/0Eh++16OZbin7CwDB8xw4Iw8L2+HttEVLJBRg5b90Gcpg/bsZME=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
