travis:
  secure:
    BINSTAR_TOKEN: fK0ibtF2+CMMZeflWggsQiaOlwtk50nER+fXS2QvW8uukEI+H05xpR0ziTryk163zd+TmwoduJeGxl1rsQpqXhSHteQ6cNEdVfWdzCUz4LySxFlwFv6JwlA4wl/lVm0Cit6u4w1Fkm1JUuYnXPO+7JIYfaYir6DpHO7OpmqyV4v85hO4IrYHurvvQbyb4eL4S9/AYv7ZmPgalE45L1vQDA1mKA5trS8IjAjcSO4a9u9/pJctMirP4RPdA3OZD8vnsyuT8OYuFBCE+1uEFV6npjnJKpi5a0UKoSVNCy9VpqdtBNc4QSu3JudlBB1psugTOibsvIDR69WeDjT2rBhqImnpclDc3gLBEUKfqb8lzvLr04WD1DEyR5cl3HHIw7632gBpAsXpKgjxlheo87NTuxaIRc+s7lnqry3AvL2QgvlJ97BPEsHpn7w277HUX8qg408XE1HZcfyxjlHdZPMTG7/nV/dxA+as2Go/HQedfofKhQQHrUkjXPfHGOeRYhEtzNCkBWo8JSjEXFX8slMtpbjAmWIsuJPepJvJX04FjplAqQ+iGRaZwnDzg7QYYRFBAkWe7IcWY0kG+vnDkPofhRvrWaYLdLHI2uHaiFWfc1oQvQmT4Ge1ag9+tfvBOcQVJ3DxKL8CyiUf/ClPId8uotVnJNbGwbip8JMPwi0FLe4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
