travis:
  secure:
    BINSTAR_TOKEN: mvDPXtcslElRPUw9/z6v3IR8Mc3eZwym+TubXisvmds/jw3gV/cASrAnKSN6T1Y3emNcIiXMMs448cyvxMtV4rJauJziGHcegLS5YxxNISSkklgzhCHLfj+oJfRu5rOyz0Zw+2E+phNP3jlMlgrKdrjgGGRwK7rcxJ/+agxio5jVj6LU6vPf8QGR1V77fKHWUxKz+s62CFrK3e8+ue565gvLX8II9K2purws5AhoekOgEZMvfu9/HcEJMn8SarTX6QyLIDzBgJ/Vzj3IYO96EXvWApHCWMhytj44ZS4t7P6m3N8D00dnXz9Q2ANC0ZepYoaLNXYANKQJZamzgdTIlg+nh7MfxHLW4RdWv+FZWVKgSiMHdeGAOR1z5150sRftvHJb1JZJFSSgG4lVO5aBxW0imhJQlI7M6EvUhUzOlpydswfoksqbsrx924Xcem+6DRJZ9zYL408tYj9kwN4NyFDrhAX9JCPghuG/OKRm1j7mKHct/d+YZ5yn0DEUOnZjL+zeZ2AuRb3A8NHf3Ye7wxmv8Crep4Ns38lLt8rhOuu/W3mtwFaPTHzo+JLESG8ZHcaFQfiTIIUfjxj/dY5ECV7S6NmS5SPVp9FOH0XELW/PLGLeFxGlBSSHd6iAlXBsZOHULjsv0O+dyP1+tLGa+h3R2k51WbjspI2S2sUcJEo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
